### ISSUE TITLE
Retry upstreaming?

### ISSUE THREAD

**Issue by Riesi** [cschuls/WineMUI#2]
Great work on fixing a wine issue!

Looking at the ML conversation and your github repo:

`FYI, this enhancement was not accepted as a patch by the Wine reviewers`

https://www.winehq.org/mailman3/hyperkitty/list/wine-devel@winehq.org/thread/I5P725ITBPF4HXIIKR7AWUOZTSEFSLRA/#FE25ZHKBKW4MCA3PH4YZ55XVT6HUN3QZ

I think there is a misunderstanding somewhere the patch didnt get NAKed.
Or maybe didnt receive the reply from Zeb?

If you still care to upstream your patch, maybe you can incorporate Zeb's comments. Her review was pretty detailed.

Also Wine now uses Gitlab :)
https://gitlab.winehq.org/wine/wine

**Comment by cschuls** [comment]
Dear Reisi,

I reviewed the linked response.  Since this was back in January of 2021, I
don't recall if I actually had seen this response since that was from two
years ago.  I vaguely recall submitting an inquiry about how proposed
enhancements could be incorporated into the Wine application, and receiving
a response back that there were strict testing procedures for which I was
not fluent in.  FYI, I am a retired engineer and programmer/analyst and the
primary language I coded in for forty plus years was IBM RPG, in its
various iterations.  The "C" programming language has always been a "fun to
play with and learn" language, so I have never really gotten proficient in
developing any "test harnesses" for that language.

However, I would gladly collaborate with someone more proficient in
building test scenarios for an enhancement such as this.  I have had no
issue with reapplying this enhancement and placing it out on GitHub for the
betterment of the Wine application, but if through collaboration and
testing, this enhancement could get integrated into the standard Wine
application, I think that would be a win for me and for the Wine community.

Feel free to contact me if you have any further questions.

Regards,

Craig

**Comment by Riesi** [comment]
Thank you for your answer!
I totally understand that creating tests and such is not simple or easy.

I will look around a bit and ask people, maybe we can get your patch or a similar solution upstream some day! :)

Kind regards,
Riesi

**Comment by cschuls** [comment]
Riesi,

Thanks for the response back.  If you can find someone with the skill set
to develop a proper test and possibly get this enhancement into the base
product, that would be awesome.  FYI, I have uploaded my enhancement/patch
for version 8.17 up to GitHub.

Kind regards,

Craig
